# Generated by Django 5.2.8 on 2025-11-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0002_contactenquiry_contactrecipientemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Anonymous session identifier used for tying together drafts and submissions.', max_length=64)),
                ('product_id', models.CharField(blank=True, help_text='Upstream product identifier (UUID or slug used with the API).', max_length=64)),
                ('product_slug', models.CharField(blank=True, help_text='SEO slug for the product detail page, when available.', max_length=255)),
                ('product_name', models.CharField(blank=True, help_text='Human‑readable product name at the time of the enquiry.', max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, help_text='One‑time / repeat or similar purchase frequency indicator.', max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('page_url', models.CharField(blank=True, help_text='Path or URL where the lead was captured.', max_length=500)),
                ('source', models.CharField(choices=[('discuss', 'Discuss form'), ('quick', 'Quick enquiry'), ('draft', 'Draft (autosave)')], default='discuss', max_length=16)),
                ('is_draft', models.BooleanField(default=False, help_text='True for autosaved partial data that has not been fully submitted yet.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the user explicitly submitted the enquiry.', null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
