# Generated by Django 5.2.8 on 2025-12-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0003_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(help_text='Tab label shown in the navigation and inside the hero area.', max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the tabs navigation.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this tab from the site without deleting it.')),
            ],
            options={
                'verbose_name': 'Tabs section tab',
                'verbose_name_plural': 'Tabs section tabs',
                'ordering': ['order', 'tab_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTabPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Upload icon image for this point (e.g. 32x32 PNG/SVG).', null=True, upload_to='tabs/points/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the order of points inside a tab.')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='globe.servicetab')),
            ],
            options={
                'verbose_name': 'Tabs section point',
                'verbose_name_plural': 'Tabs section points',
                'ordering': ['order', 'title'],
            },
        ),
    ]
