# Generated by Django 5.2.8 on 2025-12-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0004_servicetab_servicetabpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous session identifier emitted by the frontend tracker.', max_length=64)),
                ('product_id', models.CharField(blank=True, db_index=True, help_text='Upstream product identifier associated with this session.', max_length=64)),
                ('user_id', models.CharField(blank=True, help_text='Optional user identifier if the visitor is authenticated.', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, help_text='Client-side timestamp when the session started.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Client-side timestamp when the visitor left the page.', null=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('traffic_source', models.CharField(blank=True, max_length=64)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, help_text='Normalised device type (desktop / tablet / mobile).', max_length=32)),
                ('os', models.CharField(blank=True, max_length=128)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('viewport', models.CharField(blank=True, max_length=32)),
                ('orientation', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, help_text='Visitor country derived from IP at the ingest tier (optional).', max_length=64)),
                ('consent', models.BooleanField(default=False)),
                ('is_returning', models.BooleanField(default=False)),
                ('sampled', models.BooleanField(default=True)),
                ('max_scroll_pct', models.PositiveSmallIntegerField(default=0)),
                ('cta_clicks', models.PositiveIntegerField(default=0)),
                ('enquiry_submissions', models.PositiveIntegerField(default=0)),
                ('video_seconds_watched', models.PositiveIntegerField(default=0)),
                ('idle_time_ms', models.PositiveIntegerField(default=0)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('section_durations', models.JSONField(blank=True, default=dict, help_text='Mapping of section id (data-section) to dwell time in milliseconds. Used to compute most/least viewed sections and exit section.')),
                ('last_active_section', models.CharField(blank=True, help_text='Last section id that was active before the session ended.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics session',
                'verbose_name_plural': 'Analytics sessions',
                'ordering': ('-started_at', '-created_at'),
                'unique_together': {('session_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='Normalised event type, e.g. page_view, cta_click, scroll_depth.', max_length=64)),
                ('occurred_at', models.DateTimeField(help_text='Client-side timestamp when the event occurred.')),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Opaque event payload as emitted by the frontend tracker.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='globe.analyticssession')),
            ],
            options={
                'verbose_name': 'Analytics event',
                'verbose_name_plural': 'Analytics events',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='globe_analy_event_t_25217b_idx'), models.Index(fields=['session', 'event_type'], name='globe_analy_session_ceee11_idx')],
            },
        ),
    ]
