# Generated by Django 5.2.8 on 2025-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0005_analyticssession_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
