"""
Django settings for globesuggest project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dq1*jml=e3-=e5*%%6e9z5f5v4c!^xxbxl(7zsgj@z=im7^55q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["globesuggest.com", "www.globesuggest.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'globe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'globesuggest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context providing analytics configuration used by
                # `product_detail.html` for encrypted behavioural tracking.
                'globe.context_processors.analytics',
            ],
        },
    },
]

WSGI_APPLICATION = 'globesuggest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'globesuggest_db',
        'USER': 'globesuggest_user',
        'PASSWORD': 'Lemon$$11g',
        'HOST': 'localhost', 
        'PORT': '3306',       
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# External Globesuggest / 1Matrix API configuration
# Default base URL now points to the dedicated app host as requested.
GLOBESUGGEST_API_BASE = os.environ.get('GLOBESUGGEST_API_BASE', 'https://app.1matrix.io')
GLOBESUGGEST_API_KEY = os.environ.get('GLOBESUGGEST_API_KEY', 'Helpeza@2312')

# Frontend analytics configuration
# All of these can be overridden via environment variables so that
# 1matrix.io can control the ingest endpoint and crypto keys.
# NOTE: The browser now posts analytics to the local proxy
# `/api/analytics/forward/`. This setting represents the upstream
# 1matrix.io ingest URL used *by the proxy*, not by the browser.
ANALYTICS_INGEST_URL = os.environ.get(
    'ANALYTICS_INGEST_URL',
    'https://1matrix.io/api/gs-analytics/ingest/',
)
# Backwards compatible alias used by the proxy view.
ANALYTICS_REMOTE_INGEST_URL = os.environ.get(
    'ANALYTICS_REMOTE_INGEST_URL',
    ANALYTICS_INGEST_URL,
)
ANALYTICS_SAMPLE_RATE = float(os.environ.get('ANALYTICS_SAMPLE_RATE', '1.0'))
ANALYTICS_REQUIRE_CONSENT = os.environ.get('ANALYTICS_REQUIRE_CONSENT', 'false').lower() == 'true'

# IMPORTANT:
# - Replace this default with the real RSA public key for 1matrix.io
#   by setting the ANALYTICS_REMOTE_PUBLIC_KEY_PEM environment variable.
# - The corresponding private key must live only on the 1matrix.io backend.
DEFAULT_ANALYTICS_REMOTE_PUBLIC_KEY_PEM = os.environ.get('ANALYTICS_REMOTE_PUBLIC_KEY_PEM', '')

# Backwards-compatible name kept for remote public key.
ANALYTICS_PUBLIC_KEY_PEM = os.environ.get(
    'ANALYTICS_PUBLIC_KEY_PEM',
    DEFAULT_ANALYTICS_REMOTE_PUBLIC_KEY_PEM,
)

# Public key used by the frontend when encrypting payloads for 1matrix.io.
ANALYTICS_REMOTE_PUBLIC_KEY_PEM = os.environ.get(
    'ANALYTICS_REMOTE_PUBLIC_KEY_PEM',
    ANALYTICS_PUBLIC_KEY_PEM,
)

# Public / private key pair used for the local analytics ingest endpoint.
# Only the public key is ever exposed to the frontend. The private key
# must not be rendered in templates.
#
# For local development we read the PEM files generated in the project root:
#   - local_analytics_public.pem
#   - local_analytics_private.pem
# In production you should instead inject these via environment variables.
local_public_path = BASE_DIR / "local_analytics_public.pem"
local_private_path = BASE_DIR / "local_analytics_private.pem"
if local_public_path.exists() and local_private_path.exists():
    ANALYTICS_LOCAL_PUBLIC_KEY_PEM = local_public_path.read_text(encoding="utf-8")
    ANALYTICS_LOCAL_PRIVATE_KEY_PEM = local_private_path.read_text(encoding="utf-8")
else:
    ANALYTICS_LOCAL_PUBLIC_KEY_PEM = os.environ.get('ANALYTICS_LOCAL_PUBLIC_KEY_PEM', '')
    ANALYTICS_LOCAL_PRIVATE_KEY_PEM = os.environ.get('ANALYTICS_LOCAL_PRIVATE_KEY_PEM', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
